// SHJJ - South Houston Jiu-Jitsu Academy demo data
// All IDs are deterministic UUIDs for consistency

export const SCHOOL = {
  id: "a1b2c3d4-0001-4000-8000-000000000001",
  name: "South Houston Jiu-Jitsu",
  slug: "shjj",
  plan: "pro",
  plan_status: "active",
  trial_ends_at: null,
  video_limit: 100,
  storage_limit_bytes: 53687091200, // 50 GB
  created_at: "2025-06-15T10:00:00Z",
};

export const USERS = [
  {
    id: "b1b2c3d4-0001-4000-8000-000000000001",
    school_id: SCHOOL.id,
    email: "coach.marcus@shjj.com",
    name: "Coach Marcus Rivera",
    role: "admin",
    email_notifications: true,
    created_at: "2025-06-15T10:00:00Z",
  },
  {
    id: "b1b2c3d4-0002-4000-8000-000000000002",
    school_id: SCHOOL.id,
    email: "coach.ana@shjj.com",
    name: "Coach Ana Santos",
    role: "instructor",
    email_notifications: true,
    created_at: "2025-07-01T10:00:00Z",
  },
  {
    id: "b1b2c3d4-0003-4000-8000-000000000003",
    school_id: SCHOOL.id,
    email: "jake.thompson@email.com",
    name: "Jake Thompson",
    role: "student",
    email_notifications: true,
    created_at: "2025-07-10T10:00:00Z",
  },
  {
    id: "b1b2c3d4-0004-4000-8000-000000000004",
    school_id: SCHOOL.id,
    email: "sarah.chen@email.com",
    name: "Sarah Chen",
    role: "student",
    email_notifications: true,
    created_at: "2025-07-15T10:00:00Z",
  },
  {
    id: "b1b2c3d4-0005-4000-8000-000000000005",
    school_id: SCHOOL.id,
    email: "mike.johnson@email.com",
    name: "Mike Johnson",
    role: "student",
    email_notifications: true,
    created_at: "2025-08-01T10:00:00Z",
  },
  {
    id: "b1b2c3d4-0006-4000-8000-000000000006",
    school_id: SCHOOL.id,
    email: "elena.rodriguez@email.com",
    name: "Elena Rodriguez",
    role: "student",
    email_notifications: true,
    created_at: "2025-08-20T10:00:00Z",
  },
  {
    id: "b1b2c3d4-0007-4000-8000-000000000007",
    school_id: SCHOOL.id,
    email: "david.kim@email.com",
    name: "David Kim",
    role: "student",
    email_notifications: true,
    created_at: "2025-09-05T10:00:00Z",
  },
  {
    id: "b1b2c3d4-0008-4000-8000-000000000008",
    school_id: SCHOOL.id,
    email: "olivia.martinez@email.com",
    name: "Olivia Martinez",
    role: "student",
    email_notifications: true,
    created_at: "2025-09-20T10:00:00Z",
  },
  {
    id: "b1b2c3d4-0009-4000-8000-000000000009",
    school_id: SCHOOL.id,
    email: "ryan.patel@email.com",
    name: "Ryan Patel",
    role: "student",
    email_notifications: false,
    created_at: "2025-10-01T10:00:00Z",
  },
  {
    id: "b1b2c3d4-0010-4000-8000-000000000010",
    school_id: SCHOOL.id,
    email: "jasmine.wright@email.com",
    name: "Jasmine Wright",
    role: "student",
    email_notifications: true,
    created_at: "2025-10-15T10:00:00Z",
  },
];

const DEMO_ROLE = (typeof Netlify !== "undefined" && Netlify?.env?.get("DEMO_ROLE")) || "admin";

export const DEFAULT_USER = DEMO_ROLE === "student"
  ? USERS[2]  // Jake Thompson - student (has the most sessions)
  : USERS[0]; // Coach Marcus Rivera - admin

export const IS_STUDENT_DEMO = DEMO_ROLE === "student";

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split("T")[0];
}

function daysAgoISO(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

export const SESSIONS = [
  {
    id: "c1c2c3d4-0001-4000-8000-000000000001",
    school_id: SCHOOL.id,
    instructor_id: USERS[0].id,
    student_id: USERS[2].id,
    title: "Guard Passing Fundamentals",
    date: daysAgo(1),
    duration: "45 min",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["guard-passing", "fundamentals"],
    created_at: daysAgoISO(1),
    student_name: USERS[2].name,
    instructor_name: USERS[0].name,
    note_count: "3",
    viewed: true,
  },
  {
    id: "c1c2c3d4-0002-4000-8000-000000000002",
    school_id: SCHOOL.id,
    instructor_id: USERS[0].id,
    student_id: USERS[3].id,
    title: "Competition Prep - Triangle Setup",
    date: daysAgo(2),
    duration: "60 min",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["competition", "triangle", "submissions"],
    created_at: daysAgoISO(2),
    student_name: USERS[3].name,
    instructor_name: USERS[0].name,
    note_count: "5",
    viewed: true,
  },
  {
    id: "c1c2c3d4-0003-4000-8000-000000000003",
    school_id: SCHOOL.id,
    instructor_id: USERS[1].id,
    student_id: USERS[4].id,
    title: "Back Take Series",
    date: daysAgo(3),
    duration: "50 min",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["back-control", "submissions"],
    created_at: daysAgoISO(3),
    student_name: USERS[4].name,
    instructor_name: USERS[1].name,
    note_count: "2",
    viewed: false,
  },
  {
    id: "c1c2c3d4-0004-4000-8000-000000000004",
    school_id: SCHOOL.id,
    instructor_id: USERS[0].id,
    student_id: USERS[5].id,
    title: "Half Guard Sweeps",
    date: daysAgo(4),
    duration: "45 min",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["half-guard", "sweeps"],
    created_at: daysAgoISO(4),
    student_name: USERS[5].name,
    instructor_name: USERS[0].name,
    note_count: "4",
    viewed: true,
  },
  {
    id: "c1c2c3d4-0005-4000-8000-000000000005",
    school_id: SCHOOL.id,
    instructor_id: USERS[1].id,
    student_id: USERS[6].id,
    title: "Armbar from Closed Guard",
    date: daysAgo(5),
    duration: "40 min",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["armbar", "closed-guard", "fundamentals"],
    created_at: daysAgoISO(5),
    student_name: USERS[6].name,
    instructor_name: USERS[1].name,
    note_count: "3",
    viewed: true,
  },
  {
    id: "c1c2c3d4-0006-4000-8000-000000000006",
    school_id: SCHOOL.id,
    instructor_id: USERS[0].id,
    student_id: USERS[7].id,
    title: "Mount Escapes & Retention",
    date: daysAgo(6),
    duration: "55 min",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["mount", "escapes", "positional"],
    created_at: daysAgoISO(6),
    student_name: USERS[7].name,
    instructor_name: USERS[0].name,
    note_count: "2",
    viewed: false,
  },
  {
    id: "c1c2c3d4-0007-4000-8000-000000000007",
    school_id: SCHOOL.id,
    instructor_id: USERS[0].id,
    student_id: USERS[2].id,
    title: "Knee Cut Pass to Side Control",
    date: daysAgo(8),
    duration: "45 min",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["guard-passing", "knee-cut", "side-control"],
    created_at: daysAgoISO(8),
    student_name: USERS[2].name,
    instructor_name: USERS[0].name,
    note_count: "4",
    viewed: true,
  },
  {
    id: "c1c2c3d4-0008-4000-8000-000000000008",
    school_id: SCHOOL.id,
    instructor_id: USERS[1].id,
    student_id: USERS[8].id,
    title: "Takedown Defense for BJJ",
    date: daysAgo(10),
    duration: "50 min",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["takedowns", "defense", "standing"],
    created_at: daysAgoISO(10),
    student_name: USERS[8].name,
    instructor_name: USERS[1].name,
    note_count: "2",
    viewed: true,
  },
  {
    id: "c1c2c3d4-0009-4000-8000-000000000009",
    school_id: SCHOOL.id,
    instructor_id: USERS[0].id,
    student_id: USERS[9].id,
    title: "De La Riva Guard Intro",
    date: daysAgo(12),
    duration: "45 min",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["de-la-riva", "open-guard", "fundamentals"],
    created_at: daysAgoISO(12),
    student_name: USERS[9].name,
    instructor_name: USERS[0].name,
    note_count: "3",
    viewed: true,
  },
  {
    id: "c1c2c3d4-0010-4000-8000-000000000010",
    school_id: SCHOOL.id,
    instructor_id: USERS[0].id,
    student_id: USERS[3].id,
    title: "Butterfly Guard Sweeps",
    date: daysAgo(14),
    duration: "50 min",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["butterfly-guard", "sweeps"],
    created_at: daysAgoISO(14),
    student_name: USERS[3].name,
    instructor_name: USERS[0].name,
    note_count: "3",
    viewed: true,
  },
  {
    id: "c1c2c3d4-0011-4000-8000-000000000011",
    school_id: SCHOOL.id,
    instructor_id: USERS[1].id,
    student_id: USERS[4].id,
    title: "Rear Naked Choke Finishing Details",
    date: daysAgo(16),
    duration: "40 min",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["back-control", "rear-naked-choke", "submissions"],
    created_at: daysAgoISO(16),
    student_name: USERS[4].name,
    instructor_name: USERS[1].name,
    note_count: "2",
    viewed: true,
  },
  {
    id: "c1c2c3d4-0012-4000-8000-000000000012",
    school_id: SCHOOL.id,
    instructor_id: USERS[0].id,
    student_id: USERS[5].id,
    title: "Spider Guard Control & Attacks",
    date: daysAgo(18),
    duration: "55 min",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["spider-guard", "open-guard", "sweeps"],
    created_at: daysAgoISO(18),
    student_name: USERS[5].name,
    instructor_name: USERS[0].name,
    note_count: "4",
    viewed: true,
  },
  // Additional sessions for Jake Thompson (student demo richness)
  {
    id: "c1c2c3d4-0013-4000-8000-000000000013",
    school_id: SCHOOL.id,
    instructor_id: USERS[0].id,
    student_id: USERS[2].id,
    title: "Closed Guard Submissions Chain",
    date: daysAgo(0),
    duration: "50 min",
    video_key: "demo/jake-closed-guard.mp4",
    video_status: "ready",
    vimeo_id: null,
    tags: ["closed-guard", "submissions", "chain-attacks"],
    created_at: daysAgoISO(0),
    student_name: USERS[2].name,
    instructor_name: USERS[0].name,
    note_count: "4",
    viewed: false,
    last_position_seconds: 0,
  },
  {
    id: "c1c2c3d4-0014-4000-8000-000000000014",
    school_id: SCHOOL.id,
    instructor_id: USERS[1].id,
    student_id: USERS[2].id,
    title: "Side Control Escapes",
    date: daysAgo(3),
    duration: "45 min",
    video_key: "demo/jake-side-control.mp4",
    video_status: "ready",
    vimeo_id: null,
    tags: ["side-control", "escapes", "fundamentals"],
    created_at: daysAgoISO(3),
    student_name: USERS[2].name,
    instructor_name: USERS[1].name,
    note_count: "3",
    viewed: false,
    last_position_seconds: 185,
  },
  {
    id: "c1c2c3d4-0015-4000-8000-000000000015",
    school_id: SCHOOL.id,
    instructor_id: USERS[0].id,
    student_id: USERS[2].id,
    title: "Single Leg Takedown Drill",
    date: daysAgo(6),
    duration: "40 min",
    video_key: "demo/jake-single-leg.mp4",
    video_status: "ready",
    vimeo_id: null,
    tags: ["takedowns", "standing", "wrestling"],
    created_at: daysAgoISO(6),
    student_name: USERS[2].name,
    instructor_name: USERS[0].name,
    note_count: "2",
    viewed: true,
    last_position_seconds: 0,
  },
  {
    id: "c1c2c3d4-0016-4000-8000-000000000016",
    school_id: SCHOOL.id,
    instructor_id: USERS[0].id,
    student_id: USERS[2].id,
    title: "Half Guard Recovery & Sweeps",
    date: daysAgo(11),
    duration: "55 min",
    video_key: "demo/jake-half-guard.mp4",
    video_status: "ready",
    vimeo_id: null,
    tags: ["half-guard", "sweeps", "recovery"],
    created_at: daysAgoISO(11),
    student_name: USERS[2].name,
    instructor_name: USERS[0].name,
    note_count: "3",
    viewed: true,
    last_position_seconds: 0,
  },
  {
    id: "c1c2c3d4-0017-4000-8000-000000000017",
    school_id: SCHOOL.id,
    instructor_id: USERS[1].id,
    student_id: USERS[2].id,
    title: "Turtle Position & Escapes",
    date: daysAgo(15),
    duration: "45 min",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["turtle", "escapes", "defense"],
    created_at: daysAgoISO(15),
    student_name: USERS[2].name,
    instructor_name: USERS[1].name,
    note_count: "2",
    viewed: true,
    last_position_seconds: 0,
  },
  {
    id: "c1c2c3d4-0018-4000-8000-000000000018",
    school_id: SCHOOL.id,
    instructor_id: USERS[0].id,
    student_id: USERS[2].id,
    title: "Competition Prep - Game Plan Review",
    date: daysAgo(20),
    duration: "60 min",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["competition", "strategy", "game-plan"],
    created_at: daysAgoISO(20),
    student_name: USERS[2].name,
    instructor_name: USERS[0].name,
    note_count: "5",
    viewed: true,
    last_position_seconds: 0,
  },
];

export const SESSION_NOTES: Record<string, any[]> = {
  [SESSIONS[0].id]: [
    { id: "n001", session_id: SESSIONS[0].id, timestamp_seconds: 0, type: "note", text: "Focus on maintaining posture while standing in guard. Keep elbows tight and grip the lapels.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(1) },
    { id: "n002", session_id: SESSIONS[0].id, timestamp_seconds: 120, type: "key", text: "Key concept: knee-slide entry requires breaking the guard first. Use the leg weave to open.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(1) },
    { id: "n003", session_id: SESSIONS[0].id, timestamp_seconds: 300, type: "drill", text: "Drill: 5 reps each side - knee cut pass with underhook control. Partner starts in closed guard.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(1) },
  ],
  [SESSIONS[1].id]: [
    { id: "n004", session_id: SESSIONS[1].id, timestamp_seconds: 0, type: "note", text: "Sarah is preparing for the Houston Open in 3 weeks. Focus on her A-game triangle from guard.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(2) },
    { id: "n005", session_id: SESSIONS[1].id, timestamp_seconds: 60, type: "key", text: "Key adjustment: angle off at 45 degrees BEFORE locking the triangle. This eliminates the posture-up escape.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(2) },
    { id: "n006", session_id: SESSIONS[1].id, timestamp_seconds: 180, type: "drill", text: "Drill sequence: overhook -> hip escape -> shoot triangle -> adjust angle -> squeeze. 10 reps each side.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(2) },
    { id: "n007", session_id: SESSIONS[1].id, timestamp_seconds: 400, type: "note", text: "Great improvement on the angle adjustment. The squeeze is much tighter now. Keep drilling this week.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(2) },
    { id: "n008", session_id: SESSIONS[1].id, timestamp_seconds: 600, type: "key", text: "Homework: practice hip escape to triangle setup 20 times per side before next session.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(2) },
  ],
  [SESSIONS[2].id]: [
    { id: "n009", session_id: SESSIONS[2].id, timestamp_seconds: 0, type: "note", text: "Working on back takes from turtle position. Mike has good instincts but needs to control the near hip.", author_id: USERS[1].id, author_name: USERS[1].name, author_role: "instructor", created_at: daysAgoISO(3) },
    { id: "n010", session_id: SESSIONS[2].id, timestamp_seconds: 240, type: "drill", text: "Drill: seatbelt grip -> hooks in -> body triangle. 8 reps each side.", author_id: USERS[1].id, author_name: USERS[1].name, author_role: "instructor", created_at: daysAgoISO(3) },
  ],
  [SESSIONS[3].id]: [
    { id: "n011", session_id: SESSIONS[3].id, timestamp_seconds: 0, type: "note", text: "Elena has a natural feel for the underhook from half guard. Building her sweep game from this position.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(4) },
    { id: "n012", session_id: SESSIONS[3].id, timestamp_seconds: 90, type: "key", text: "Critical detail: get the underhook DEEP and stay on the side. Flat = no sweep.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(4) },
    { id: "n013", session_id: SESSIONS[3].id, timestamp_seconds: 200, type: "drill", text: "Drill: Old School sweep from half guard. Focus on the knee tap and hip drive. 6 reps each side.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(4) },
    { id: "n014", session_id: SESSIONS[3].id, timestamp_seconds: 400, type: "note", text: "Also introduced the Plan B sweep (electric chair) when they whizzer. Elena picked it up quickly.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(4) },
  ],
  [SESSIONS[4].id]: [
    { id: "n015", session_id: SESSIONS[4].id, timestamp_seconds: 0, type: "note", text: "David is still early in his journey. Focusing on the basic armbar mechanics from closed guard.", author_id: USERS[1].id, author_name: USERS[1].name, author_role: "instructor", created_at: daysAgoISO(5) },
    { id: "n016", session_id: SESSIONS[4].id, timestamp_seconds: 150, type: "key", text: "Key: pinch the knees and keep hips high. The squeeze comes from the hips, not the arms.", author_id: USERS[1].id, author_name: USERS[1].name, author_role: "instructor", created_at: daysAgoISO(5) },
    { id: "n017", session_id: SESSIONS[4].id, timestamp_seconds: 350, type: "drill", text: "Drill: armbar from guard with hip bump setup. 8 reps each side, slow and controlled.", author_id: USERS[1].id, author_name: USERS[1].name, author_role: "instructor", created_at: daysAgoISO(5) },
  ],
  [SESSIONS[12].id]: [
    { id: "n018", session_id: SESSIONS[12].id, timestamp_seconds: 0, type: "note", text: "Jake is showing real progress in closed guard. Today we chain submissions together: collar choke -> armbar -> triangle.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(0) },
    { id: "n019", session_id: SESSIONS[12].id, timestamp_seconds: 90, type: "key", text: "Key: when the collar choke attempt makes them posture up, immediately transition to armbar. The reaction IS the setup.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(0) },
    { id: "n020", session_id: SESSIONS[12].id, timestamp_seconds: 240, type: "drill", text: "Drill chain: collar choke attempt -> they posture -> armbar attempt -> they stack -> triangle. 6 reps each side.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(0) },
    { id: "n021", session_id: SESSIONS[12].id, timestamp_seconds: 500, type: "note", text: "Excellent work today. The chain is becoming second nature. Focus on the hip escape timing for the armbar transition this week.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(0) },
  ],
  [SESSIONS[13].id]: [
    { id: "n022", session_id: SESSIONS[13].id, timestamp_seconds: 0, type: "note", text: "Side control escapes - Jake's weakest position. Working on the hip escape to guard recovery.", author_id: USERS[1].id, author_name: USERS[1].name, author_role: "instructor", created_at: daysAgoISO(3) },
    { id: "n023", session_id: SESSIONS[13].id, timestamp_seconds: 120, type: "key", text: "Critical detail: frame on the hip and bicep BEFORE bridging. Bridge without frames = wasted energy.", author_id: USERS[1].id, author_name: USERS[1].name, author_role: "instructor", created_at: daysAgoISO(3) },
    { id: "n024", session_id: SESSIONS[13].id, timestamp_seconds: 300, type: "drill", text: "Drill: frame -> bridge -> hip escape to half guard -> recover full guard. 8 reps each side, increasing resistance.", author_id: USERS[1].id, author_name: USERS[1].name, author_role: "instructor", created_at: daysAgoISO(3) },
  ],
  [SESSIONS[14].id]: [
    { id: "n025", session_id: SESSIONS[14].id, timestamp_seconds: 0, type: "note", text: "Working on the single leg takedown. Jake has good wrestling instincts.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(6) },
    { id: "n026", session_id: SESSIONS[14].id, timestamp_seconds: 200, type: "drill", text: "Drill: level change -> penetration step -> head on the inside -> run the pipe. 10 reps each side.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(6) },
  ],
  [SESSIONS[15].id]: [
    { id: "n027", session_id: SESSIONS[15].id, timestamp_seconds: 0, type: "note", text: "Half guard is becoming Jake's go-to recovery position. Building sweep options from here.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(11) },
    { id: "n028", session_id: SESSIONS[15].id, timestamp_seconds: 150, type: "key", text: "Key concept: always fight for the underhook from half guard bottom. Underhook = sweeps. No underhook = getting smashed.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(11) },
    { id: "n029", session_id: SESSIONS[15].id, timestamp_seconds: 350, type: "drill", text: "Drill: underhook fight -> come to knees -> Old School sweep. Then underhook -> knee tap sweep. 6 reps each.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(11) },
  ],
  [SESSIONS[17].id]: [
    { id: "n030", session_id: SESSIONS[17].id, timestamp_seconds: 0, type: "note", text: "Competition prep for Jake. He's competing in the intermediate division at the Houston Open next month.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(20) },
    { id: "n031", session_id: SESSIONS[17].id, timestamp_seconds: 60, type: "key", text: "Game plan: pull guard -> closed guard attack chain (collar choke -> armbar -> triangle). If on top: knee cut pass to side control.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(20) },
    { id: "n032", session_id: SESSIONS[17].id, timestamp_seconds: 180, type: "note", text: "Backup plan: if guard pull fails, snap down to front headlock. Jake's guillotine is getting sharp.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(20) },
    { id: "n033", session_id: SESSIONS[17].id, timestamp_seconds: 400, type: "drill", text: "Competition simulation: 5 min rounds, full resistance. Score-focused rolling with penalty for pulling guard without a plan.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(20) },
    { id: "n034", session_id: SESSIONS[17].id, timestamp_seconds: 600, type: "key", text: "Homework: visualize the game plan nightly. 20 guard pull -> attack chain reps. 10 knee cut pass reps. Journal after each training session.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(20) },
  ],
};

export const CLASSES = [
  {
    id: "d1d2d3d4-0001-4000-8000-000000000001",
    school_id: SCHOOL.id,
    instructor_id: USERS[0].id,
    title: "Saturday Morning Open Mat Highlights",
    date: daysAgo(2),
    duration: "90 min",
    description: "Highlights from our Saturday open mat. Great rolls and technique exchanges between all belt levels.",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["open-mat", "rolling"],
    created_at: daysAgoISO(2),
    instructor_name: USERS[0].name,
    note_count: "3",
    viewed: true,
  },
  {
    id: "d1d2d3d4-0002-4000-8000-000000000002",
    school_id: SCHOOL.id,
    instructor_id: USERS[0].id,
    title: "Guard Retention Masterclass",
    date: daysAgo(5),
    duration: "60 min",
    description: "Fundamental guard retention concepts. How to frame, hip escape, and re-guard when your opponent is passing.",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["guard-retention", "fundamentals", "defense"],
    created_at: daysAgoISO(5),
    instructor_name: USERS[0].name,
    note_count: "4",
    viewed: true,
  },
  {
    id: "d1d2d3d4-0003-4000-8000-000000000003",
    school_id: SCHOOL.id,
    instructor_id: USERS[1].id,
    title: "No-Gi Guillotine Variations",
    date: daysAgo(7),
    duration: "50 min",
    description: "Standing, seated, and Marcelotine variations. High percentage finishes for all levels.",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["no-gi", "guillotine", "submissions"],
    created_at: daysAgoISO(7),
    instructor_name: USERS[1].name,
    note_count: "2",
    viewed: false,
  },
  {
    id: "d1d2d3d4-0004-4000-8000-000000000004",
    school_id: SCHOOL.id,
    instructor_id: USERS[0].id,
    title: "Competition Strategy & Mindset",
    date: daysAgo(10),
    duration: "45 min",
    description: "Mental preparation for tournaments. Game planning, warm-up routines, and managing nerves on competition day.",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["competition", "mindset", "strategy"],
    created_at: daysAgoISO(10),
    instructor_name: USERS[0].name,
    note_count: "3",
    viewed: true,
  },
  {
    id: "d1d2d3d4-0005-4000-8000-000000000005",
    school_id: SCHOOL.id,
    instructor_id: USERS[1].id,
    title: "Fundamentals Class - Week 12",
    date: daysAgo(14),
    duration: "60 min",
    description: "Closed guard bottom: cross collar choke, armbar, and hip bump sweep. The holy trinity for beginners.",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["fundamentals", "closed-guard", "beginners"],
    created_at: daysAgoISO(14),
    instructor_name: USERS[1].name,
    note_count: "5",
    viewed: true,
  },
  {
    id: "d1d2d3d4-0006-4000-8000-000000000006",
    school_id: SCHOOL.id,
    instructor_id: USERS[0].id,
    title: "Leg Lock Defense & Awareness",
    date: daysAgo(18),
    duration: "55 min",
    description: "Understanding leg lock positions, when you're in danger, and safe escape routes. Critical knowledge for all belts.",
    video_key: null,
    video_status: null,
    vimeo_id: null,
    tags: ["leg-locks", "defense", "awareness"],
    created_at: daysAgoISO(18),
    instructor_name: USERS[0].name,
    note_count: "3",
    viewed: true,
  },
];

export const CLASS_NOTES: Record<string, any[]> = {
  [CLASSES[0].id]: [
    { id: "cn001", class_id: CLASSES[0].id, timestamp_seconds: 0, type: "note", text: "Great energy on the mats today. Good to see upper belts working with white belts.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(2) },
    { id: "cn002", class_id: CLASSES[0].id, timestamp_seconds: 180, type: "key", text: "Reminder: when rolling with lower belts, focus on positions and transitions rather than submissions.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(2) },
    { id: "cn003", class_id: CLASSES[0].id, timestamp_seconds: 400, type: "note", text: "Several students showed great improvement in hip escapes. The drilling from last week is paying off.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(2) },
  ],
  [CLASSES[1].id]: [
    { id: "cn004", class_id: CLASSES[1].id, timestamp_seconds: 0, type: "note", text: "Guard retention is the most underrated skill in BJJ. Today we cover the fundamentals.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(5) },
    { id: "cn005", class_id: CLASSES[1].id, timestamp_seconds: 90, type: "key", text: "The 3 principles of guard retention: 1) face your opponent, 2) keep frames active, 3) move your hips.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(5) },
    { id: "cn006", class_id: CLASSES[1].id, timestamp_seconds: 250, type: "drill", text: "Drill: partner passes, you re-guard. Start light, increase resistance. 3 min rounds, 4 rounds each.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(5) },
    { id: "cn007", class_id: CLASSES[1].id, timestamp_seconds: 500, type: "note", text: "Common mistake: turning away from the passer. Always face your opponent and maintain eye contact.", author_id: USERS[0].id, author_name: USERS[0].name, author_role: "admin", created_at: daysAgoISO(5) },
  ],
  [CLASSES[2].id]: [
    { id: "cn008", class_id: CLASSES[2].id, timestamp_seconds: 0, type: "note", text: "The guillotine is one of the most versatile submissions. Works from standing, half guard, and guard.", author_id: USERS[1].id, author_name: USERS[1].name, author_role: "instructor", created_at: daysAgoISO(7) },
    { id: "cn009", class_id: CLASSES[2].id, timestamp_seconds: 200, type: "key", text: "For the Marcelotine: chin strap grip, not the throat. Pull the elbow to your hip and arch your back.", author_id: USERS[1].id, author_name: USERS[1].name, author_role: "instructor", created_at: daysAgoISO(7) },
  ],
};

export const STATS = {
  total_members: String(USERS.length),
  total_students: String(USERS.filter(u => u.role === "student").length),
  total_instructors: String(USERS.filter(u => u.role === "instructor" || u.role === "admin").length),
  total_sessions: String(SESSIONS.length),
  total_classes: String(CLASSES.length),
  total_session_notes: String(Object.values(SESSION_NOTES).flat().length),
  total_class_notes: String(Object.values(CLASS_NOTES).flat().length),
};

export const ACTIVITY = {
  recentSessions: SESSIONS.slice(0, 5).map(s => ({
    id: s.id,
    title: s.title,
    student_name: s.student_name,
    date: s.date,
    completed_count: 1,
  })),
  recentClasses: CLASSES.slice(0, 3).map(c => ({
    id: c.id,
    title: c.title,
    date: c.date,
    total_students: USERS.filter(u => u.role === "student").length,
    completed_count: Math.floor(Math.random() * 5) + 2,
    view_count: Math.floor(Math.random() * 8) + 3,
  })),
  sessionViews: SESSIONS.slice(0, 3).map(s => ({
    session_id: s.id,
    session_title: s.title,
    student_name: s.student_name,
    user_id: s.student_id,
    completed: true,
    viewed_at: s.created_at,
  })),
  classViews: CLASSES.slice(0, 2).map(c => ({
    class_id: c.id,
    class_title: c.title,
    student_name: USERS[2].name,
    user_id: USERS[2].id,
    completed: true,
    viewed_at: c.created_at,
  })),
};

export const TAGS = [
  "fundamentals", "guard-passing", "submissions", "competition",
  "triangle", "back-control", "half-guard", "sweeps",
  "armbar", "closed-guard", "mount", "escapes",
  "positional", "knee-cut", "side-control", "takedowns",
  "defense", "standing", "de-la-riva", "open-guard",
  "butterfly-guard", "rear-naked-choke", "spider-guard",
  "no-gi", "guillotine", "mindset", "strategy",
  "leg-locks", "awareness", "beginners", "rolling", "open-mat",
  "guard-retention",
];

export const VIDEO_USAGE = {
  videoCount: 4,
  storageUsed: 2147483648, // ~2 GB
  videoLimit: SCHOOL.video_limit,
  storageLimitBytes: SCHOOL.storage_limit_bytes,
};
